/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package duan1;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author MSI8
 */
public class nhanvien1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form nhanvien
     */
    public nhanvien1() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtName3 = new javax.swing.JTextField();
        rdMale2 = new javax.swing.JRadioButton();
        rdFemale2 = new javax.swing.JRadioButton();
        txtPhone2 = new javax.swing.JTextField();
        txtUser2 = new javax.swing.JTextField();
        txtPass4 = new javax.swing.JPasswordField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        txtPass5 = new javax.swing.JPasswordField();
        txtEmail2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tarAddress2 = new javax.swing.JTextArea();
        btnAdd4 = new javax.swing.JButton();
        btnReset3 = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();
        btnLuu2 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        lbHinh2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(214, 226, 238));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Giới tính:");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("Ngày sinh:");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("SDT:");

        txtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName3txtName1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMale2);
        rdMale2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdMale2.setForeground(new java.awt.Color(255, 255, 255));
        rdMale2.setSelected(true);
        rdMale2.setText("Nam");

        buttonGroup1.add(rdFemale2);
        rdFemale2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdFemale2.setForeground(new java.awt.Color(255, 255, 255));
        rdFemale2.setText("Nữ");

        txtPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone2txtPhoneActionPerformed(evt);
            }
        });

        txtUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser2txtUserActionPerformed(evt);
            }
        });

        txtPass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass4txtPassActionPerformed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("Tài khoản:");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setText("Mật khẩu:");

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel63.setText("Xác nhận mật khẩu:");

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel64.setText("Email:");

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("Địa chỉ:");

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Họ và tên:");

        txtPass5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass5txtPass1ActionPerformed(evt);
            }
        });

        txtEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail2txtEmailActionPerformed(evt);
            }
        });

        tarAddress2.setColumns(20);
        tarAddress2.setRows(5);
        jScrollPane6.setViewportView(tarAddress2);

        btnAdd4.setBackground(new java.awt.Color(188, 173, 175));
        btnAdd4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd4.setText("Thêm");
        btnAdd4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4btnAdd2ActionPerformed(evt);
            }
        });

        btnReset3.setBackground(new java.awt.Color(188, 173, 175));
        btnReset3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset3.setText("Làm mới");
        btnReset3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset3btnReset1ActionPerformed(evt);
            }
        });

        btnEdit2.setBackground(new java.awt.Color(188, 173, 175));
        btnEdit2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit2.setText("Sửa  ");
        btnEdit2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2btnEditActionPerformed(evt);
            }
        });

        btnLuu2.setBackground(new java.awt.Color(188, 173, 175));
        btnLuu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu2.setText("Lưu  ");
        btnLuu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu2btnLuuActionPerformed(evt);
            }
        });

        btnDelete2.setBackground(new java.awt.Color(188, 173, 175));
        btnDelete2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete2.setText("Xóa ");
        btnDelete2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2btnDeleteActionPerformed(evt);
            }
        });

        lbHinh2.setBackground(new java.awt.Color(204, 204, 204));
        lbHinh2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel62)
                                            .addComponent(jLabel61))
                                        .addGap(69, 69, 69))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel64)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel65))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail2)
                                    .addComponent(txtUser2)
                                    .addComponent(txtPass4)
                                    .addComponent(txtPass5)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel66)
                                                .addComponent(jLabel58)
                                                .addComponent(jLabel60))
                                            .addGap(73, 73, 73)
                                            .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(rdMale2)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdFemale2))
                                            .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(77, 77, 77)
                        .addComponent(lbHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAdd4)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete2)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset3)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu2)))
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(rdMale2)
                            .addComponent(rdFemale2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd4)
                    .addComponent(btnEdit2)
                    .addComponent(btnDelete2)
                    .addComponent(btnReset3)
                    .addComponent(btnLuu2))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thông tin", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName3txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName3txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName3txtName1ActionPerformed

    private void txtPhone2txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhone2txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhone2txtPhoneActionPerformed

    private void txtUser2txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser2txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser2txtUserActionPerformed

    private void txtPass4txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass4txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass4txtPassActionPerformed

    private void txtPass5txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass5txtPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass5txtPass1ActionPerformed

    private void txtEmail2txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail2txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail2txtEmailActionPerformed

    private void btnAdd4btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4btnAdd2ActionPerformed

    }//GEN-LAST:event_btnAdd4btnAdd2ActionPerformed

    private void btnReset3btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset3btnReset1ActionPerformed

    }//GEN-LAST:event_btnReset3btnReset1ActionPerformed

    private void btnEdit2btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2btnEditActionPerformed

    }//GEN-LAST:event_btnEdit2btnEditActionPerformed

    private void btnLuu2btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu2btnLuuActionPerformed

    }//GEN-LAST:event_btnLuu2btnLuuActionPerformed

    private void btnDelete2btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete2btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnLuu2;
    private javax.swing.JButton btnReset3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbHinh2;
    private javax.swing.JRadioButton rdFemale2;
    private javax.swing.JRadioButton rdMale2;
    private javax.swing.JTextArea tarAddress2;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JPasswordField txtPass4;
    private javax.swing.JPasswordField txtPass5;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtUser2;
    // End of variables declaration//GEN-END:variables
}
